import AuthenticationCheckProvider from '@/context/Authentication/AuthenticationCheckProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthenticationCheckProvider>
      <html lang="en">
        <body className="h-full">
          <ToastContainer />
          {
            children
          }
        </body>
      </html>
    </AuthenticationCheckProvider>
  )
}
